---
deployment:
  tasks:
    - export DEPLOYPATH=/home/idealmar/public_html/api.sevn.lk/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH